name: recipe_sharing_app
description: A comprehensive recipe sharing application with cooking tools.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1

  # Database
  path: ^1.8.3

  # Security for password hashing
  crypto: ^3.0.3

  # UI Components
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # HTTP requests (for future API integration)
  http: ^1.1.0

  # Local storage
  shared_preferences: ^2.2.2

  # Notifications (for timer alerts)
  flutter_local_notifications: ^17.0.0

  # Permission handling
  permission_handler: ^11.3.0

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/recipes_images/
    - assets/db/

  # Fonts (optional custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700