// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBajUaz8RTl4Jj2KwU8l0XSfn0fxLXFZT0',
    appId: '1:494223958059:web:c832aa04eb744ecb3fca6e',
    messagingSenderId: '494223958059',
    projectId: 'cook-pal-cae86',
    authDomain: 'cook-pal-cae86.firebaseapp.com',
    storageBucket: 'cook-pal-cae86.firebasestorage.app',
    measurementId: 'G-XWRRPP0HGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWW1WnMvNpS2zAVBCq0ld5AYj5Qw8xpU',
    appId: '1:494223958059:android:471f719373ebfc653fca6e',
    messagingSenderId: '494223958059',
    projectId: 'cook-pal-cae86',
    storageBucket: 'cook-pal-cae86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDom61c1N6JeNcmUoJok-IBYBxzfcVPYSE',
    appId: '1:494223958059:ios:0a5c151fc284fad53fca6e',
    messagingSenderId: '494223958059',
    projectId: 'cook-pal-cae86',
    storageBucket: 'cook-pal-cae86.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDom61c1N6JeNcmUoJok-IBYBxzfcVPYSE',
    appId: '1:494223958059:ios:0a5c151fc284fad53fca6e',
    messagingSenderId: '494223958059',
    projectId: 'cook-pal-cae86',
    storageBucket: 'cook-pal-cae86.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBajUaz8RTl4Jj2KwU8l0XSfn0fxLXFZT0',
    appId: '1:494223958059:web:8cfda384481312083fca6e',
    messagingSenderId: '494223958059',
    projectId: 'cook-pal-cae86',
    authDomain: 'cook-pal-cae86.firebaseapp.com',
    storageBucket: 'cook-pal-cae86.firebasestorage.app',
    measurementId: 'G-Q4KPT4BZ3J',
  );
}
